repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: double-quote-string-fixer
  - id: name-tests-test
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.1.0
  hooks:
  - id: reorder-python-imports
    files: ^airflow/dags/*\.py$
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.2.3
  hooks:
  - id: add-trailing-comma
    files: ^airflow/dags/*\.py$
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.6.0
  hooks:
  - id: autopep8
    files: ^airflow/dags/*\.py$
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    files: ^airflow/dags/*\.py$
